### ISSUE TITLE
Version file not readable

### ISSUE THREAD

**Issue by dxd1** [boxt/kaminari-api-meta-data#2]
I'm new to ruby and rails, so I might be doing something wrong, but when I install the gem I get this:
```
There was an error while trying to load the gem 'kaminari_api_meta_data'. (Bundler::GemRequireError)
Gem Load Error is: No such file or directory @ rb_sysopen - VERSION
Backtrace for gem load error is:
/var/lib/gems/2.5.0/gems/kaminari-api-meta-data-0.4.2/lib/kaminari_api_meta_data/version.rb:2:in `read'
/var/lib/gems/2.5.0/gems/kaminari-api-meta-data-0.4.2/lib/kaminari_api_meta_data/version.rb:2:in `<module:KaminariApiMetaData>'
/var/lib/gems/2.5.0/gems/kaminari-api-meta-data-0.4.2/lib/kaminari_api_meta_data/version.rb:1:in `<top (required)>'
```
Rails 5.2.3
ruby 2.5.1p57
Bundler 1.16.4

**Comment by schinery** [comment]
Hey @dxd1, it's definitely nothing you've done wrong! Was the way the `VERSION` file was being read, which used to work as is but now doesn't. Had this issue in some other gems but this one didn't get updated.

Please can you bump the version you are using to `0.5.0` and  try again?

**Comment by dxd1** [comment]
Thank you @schinery for the fix. 👍
